apiVersion: batch/v1
kind: Job
metadata:
  generateName: "santacoder-xl-v1-job-liuqian-g8"
  labels:
    estimated-running-time: "384h"
spec:
  # time to clear the job after a job is finished (completed / failed)
  ttlSecondsAfterFinished: 6048000
  template:
    spec:
      # by default priorityClassName is high
      # if quota is not enough, please set this to low to launch the job
      priorityClassName: high
      # maximum job runtime in seconds
      activeDeadlineSeconds: 6048000
      # time for prestop command execution before a container is killed
      terminationGracePeriodSeconds: 300
      containers:
      - name: "prefrl-v1"
        image: "us-docker.pkg.dev/sail-tpu-02/test-lambda/liuqian/apex-2211"
        command: ["/bin/sh", "-c", "sleep 6048000"]
        imagePullPolicy: Always
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: ""
        resources:
          # set the least amount of resources required. 
          # Please set the same number of nvidia.com/gpu for both the request and the limit
          requests:
            memory: "512Gi"
            cpu: "64"
            nvidia.com/gpu: "8"
          limits:
            memory: "512Gi"
            cpu: "64"
            nvidia.com/gpu: "8"
        volumeMounts:
          # name need to match volume name below
          # for user liumh and its group, set 1000, liumh has root privilege
        - name: workspace-vol
          mountPath: /home/liuqian/SantaCoder
          readOnly: false
        - name: shm
          mountPath: /dev/shm
        - name: cache
          mountPath: /dev/cache
        - name: cache-sail
          mountPath: /dev/cache_sail
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0 # 1000

      imagePullSecrets:
      - name: gitlab-cr-pull-secret
      - name: regcred
      restartPolicy: Never
      volumes:
      - name: workspace-vol
        hostPath:
          path: /mnt/home/liuqian/qian/SantaCoder
          type: Directory 
      - name: shm
        emptyDir:
          medium: Memory
      - name: cache
        hostPath:
          path: /mnt/cache
      - name: cache-sail
        hostPath:
          path: /mnt/cache_sail

  backoffLimit: 0
